<?php
		include('partsIn/performerTitle2.php');
?>	
<?php
		include('partsIn/AnB2.php');
?>
<?php
		include('partsIn/LblNoSlvIN2.php');
?>
<?php
		include('partsIn/gradeRadios2.php');
?>
<fieldset class="insideFields"><legend>Comment Drawers</legend>
<?php
	include("partsIn/panels.php");
?>
</fieldset>
<?php
		include("partsIn/linkboxes2.php");
?>
<?php
		include("partsIn/picasaImage2.php");
?>