<?php
		include('partsIn/performerTitle2.php');
?>
<?php
		include('partsIn/punkArtists.php');
?>	
<?php
		include('partsIn/AnB2.php');
?>
<?php
		include('partsIn/LblNoSlvIN2.php');
?>
<?php
		include('partsIn/gradeRadios2.php');
?>
<?php
	include("partsIn/panels.php");
?>
<?php
		include("partsIn/linkboxes2.php");
?>
<?php
		include("partsIn/picasaImage2.php");
?>